jaffle_shop:
  target: local
  outputs:
    local:
      type: bigquery
      method: oauth
      project: hellogoogle
      dataset: wedontwantthis
      location: europe-west1
      priority: interactive
      threads: 4